name: vqvae
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python<3.11
  - pytorch-cuda
  - torchaudio>=2.0.1
  - pytorch>=2.0.0
  - torchvision>=0.15.1
  - cupy
  - pkg-config
  - libjpeg-turbo>=2.1.4
  - opencv
  - numba==0.56.2
  - pytorch-lightning>=2.0.0
  - einops
  - kornia
  - cudatoolkit-dev
  - wandb
  - scipy
  - ninja
  - matplotlib
  - pip
  - pip:
    - ffcv>=1.0.0
    - ffcv_pl
    - lightning-utilities
    - torch-fidelity
    - scheduling_utils
