dataset:
  image_size: 256
  batch_size: 64
model:
  num_downsamples: 3      # encoded image will be image_size // (2**num_downsamples)
  latent_size: 64         # dimension of final channels
  num_residual_layers: 2
  num_embeddings: 1024    # total size of the codebook
hparams:
  lr: 2e-4
  early_stopping_patience: 6